<!DOCTYPE html>
<html lang="zh-TW"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>分發管理</title><link rel="stylesheet" href="<?= base_url('assets/css/admin.css') ?>"></head><body>
<header class="sys-navbar"><div class="sys-navbar__inner"><div class="sys-navbar__brand"><h1 class="sys-navbar__title">分發管理</h1><span class="sys-navbar__badge">Admin Portal</span></div><div class="sys-navbar__user"><a class="sys-navbar__link" href="/AdminController/scoring">學生評分</a><a class="sys-navbar__link" href="/AdminController/preferences">志願序</a><a class="sys-navbar__link" href="/AdminController">返回後台</a></div></div></header>
<main class="admin-shell"><div class="page-header"><div><h2 class="page-header__title">成績分發</h2><p>依總分由高至低，同分依固定抽籤序號，再取得該生最高且尚有名額的志願。</p></div></div>
<?php if (session()->getFlashdata('success')): ?><div class="alert alert--success"><?= esc(session()->getFlashdata('success')) ?></div><?php endif; ?>
<?php if (session()->getFlashdata('error')): ?><div class="alert alert--error"><?= esc(session()->getFlashdata('error')) ?></div><?php endif; ?>
<section class="stats-grid"><div class="stat-card"><strong><?= (int) $submitted ?></strong><span class="stat-card__label">已送出志願</span></div><div class="stat-card"><strong><?= (int) $confirmed ?></strong><span class="stat-card__label">已確認評分</span></div><div class="stat-card"><strong><?= max(0, (int)$submitted-(int)$confirmed) ?></strong><span class="stat-card__label">尚未確認</span></div></section>
<section class="admin-panel"><div class="admin-panel__header"><h3 class="admin-panel__title">建立新預覽</h3></div><div class="admin-panel__body"><form method="post" action="/AdminController/allocation/preview"><?= csrf_field() ?><button class="btn btn--primary" <?= $submitted === 0 || $submitted !== $confirmed ? 'disabled' : '' ?>>執行分發預覽</button><?php if ($submitted !== $confirmed): ?><p class="form-hint">所有已送出志願的學生都完成確認評分後才能執行。</p><?php endif; ?></form></div></section>
<?php if ($run): ?><section class="admin-panel"><div class="admin-panel__header"><h3 class="admin-panel__title">批次 #<?= (int)$run['id'] ?>（<?= esc($run['status']) ?>）</h3></div><div class="admin-panel__body">
<p class="form-hint">建立時間：<?= esc($run['started_at']) ?>　抽籤 seed：<code><?= esc($run['random_seed']) ?></code></p>
<?php if ($run['status'] === 'preview'): ?><form method="post" action="/AdminController/allocation/<?= (int)$run['id'] ?>/publish" onsubmit="return confirm('發布後學生將立即看到結果，確定發布？')"><?= csrf_field() ?><div class="form-field"><label>版本說明</label><input name="revision_note" maxlength="1000" placeholder="例如：第一次正式分發"></div><button class="btn btn--primary">正式發布結果</button></form><?php endif; ?>
<div class="table-responsive"><table class="data-table"><thead><tr><th>排名</th><th>學生</th><th>分數</th><th>同分序號</th><th>結果</th><th>志願順位</th></tr></thead><tbody><?php foreach($results as $row): ?><tr><td><?= (int)$row['overall_rank'] ?></td><td><?= esc($row['student_name']) ?><br><small><?= esc($row['student_number']) ?></small></td><td><?= esc($row['score_snapshot']) ?></td><td><code><?= esc(substr($row['lottery_order'],0,10)) ?></code></td><td><?= $row['result_status']==='admitted' ? esc($row['university_name_snapshot']) : '未分發' ?></td><td><?= $row['preference_rank'] ? '第 '.(int)$row['preference_rank'].' 志願' : '—' ?></td></tr><?php endforeach; ?></tbody></table></div>
</div></section><?php endif; ?>
<?php if ($runs): ?><section class="admin-panel"><div class="admin-panel__header"><h3 class="admin-panel__title">歷史批次</h3></div><div class="admin-panel__body"><?php foreach($runs as $item): ?><a class="btn btn--secondary btn--sm" href="?run=<?= (int)$item['id'] ?>">#<?= (int)$item['id'] ?> <?= esc($item['status']) ?></a> <?php endforeach; ?></div></section><?php endif; ?>
</main></body></html>
